name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  dio: ^5.4.1
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  google_fonts: 6.1.0
  geocoding: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_gen:
  output: lib/core/constants/
